In [ ]:
url = "https://eschome.net/databaseoutput431.php"  # replace with correct PHP script

# Example payloads
years = ["2025F", 
    "2024F",
    "2023F",
    "2022F", "2022SF2", "2022SF1",
    "2021F", "2021SF2", "2021SF1",
    "2019F", "2019SF2", "2019SF1",
    "2018F", "2018SF2", "2018SF1",
    "2017F", "2017SF2", "2017SF1",
    "2016F", "2016SF2", "2016SF1"
]
headers = {"User-Agent": "Mozilla/5.0"}

columns = ["Place", "Place_Jury", "Place_Televote", "Place_Diff",
           "Points", "Points_Jury", "Points_Televote", "Points_Diff",
           "Flag", "Country", "Performer", "Song", "Qualification",
           "Composer", "Writer", "Year"]

df = pd.DataFrame(columns=columns)

In [ ]:
for year in years:
    payload = {
        "jahr": year,
        "details": 0   # match the form checkbox for "with details"
    }
    
    r = requests.post(url, data=payload, headers=headers)
    html = r.text
    
    soup = BeautifulSoup(html, "lxml")
    table = soup.find("table", id="tabelle1")
    
    if not table:
        continue

    trs = table.find_all("tr")
    i = 0
    rows = []

    while i < len(trs):
        main_cells = trs[i].find_all("td")
        main_data = [c.get_text(strip=True) for c in main_cells]

        # Initialize detail fields
        composer = ""
        writer = ""
        qualification = ""
        
        # Look ahead: next row might contain composer/writer
        if i + 1 < len(trs):
            next_cells = trs[i + 1].find_all("td")
            next_texts = [c.get_text(strip=True) for c in next_cells]

            # Detect detail row: first several cells empty
            if all(x == "" for x in next_texts[:10]):
                composer = next_texts[10] if len(next_texts) > 10 else ""
                writer = next_texts[11] if len(next_texts) > 11 else ""
                i += 1  # skip detail row
                
        if main_data:
            row = []
            if len(main_data) < 13:
                # Combine everything + year
                row = main_data + [qualification, composer, writer, year]
            elif len(main_data) >= 13:
                row = main_data + [composer, writer, year]

            rows.append(row)

        i += 1

    # Decide which columns to use
    if len(rows[0]) == len(columns):
        df = pd.concat([df, pd.DataFrame(rows, columns=columns)], ignore_index=True)

In [ ]:
print(df.head())

In [ ]:
df.to_csv("eurovision_results2.csv", index=False)

In [44]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [45]:
import matplotlib.pyplot as plt

In [46]:
from rapidfuzz import process, fuzz

In [47]:
df_results = pd.read_csv("./eurovision_results.csv")

In [48]:
df_results_modified = df_results[["Place", "Place_Jury", "Place_Televote", "Place_Diff","Country", "Song", "Performer", "Year"]]

In [49]:
df_results_modified.head()

,Place,Place_Jury,Place_Televote,Place_Diff,Country,Song,Performer,Year
0,1,1,4,3,Austria,Wasted Love,JJ,2025F
1,2,15,1,14,Israel,New Day Will Rise,Yuval Raphael,2025F
2,3,9,2,7,Estonia,Espresso Macchiato,Tommy Cash,2025F
3,4,6,3,3,Sweden,Bara Bada Bastu,KAJ,2025F
4,5,4,10,6,Italy,Volevo Essere Un Duro,Lucio Corsi,2025F

In [50]:
years = [2016, 2017, 2018, 2019, 2021, 2022, 2023]

dfs_list = []

for yr in years:
    # Filter rows for that year
    df_year = df_results_modified[df_results_modified["Year"] == str(yr) + 'F'].copy()
    dfs_list.append(df_year)

# Concatenate all years
df_results_modified = pd.concat(dfs_list, ignore_index=True)

In [51]:
df_results_modified.head()

,Place,Place_Jury,Place_Televote,Place_Diff,Country,Song,Performer,Year
0,1,2,2,0,Ukraine,1944,Jamala,2016F
1,2,1,4,3,Australia,Sound Of Silence,Dami Im,2016F
2,3,5,1,4,Russia,You Are The Only One,Sergey Lazarev,2016F
3,4,7,5,2,Bulgaria,If Love Was A Crime,Poli Genova,2016F
4,5,9,6,3,Sweden,If I Were Sorry,Frans,2016F

In [52]:
df_pl_2016 = pd.read_csv("./Kaggle_Dataset/Polls/2016_poll_results.csv")
df_pl_2017 = pd.read_csv("./Kaggle_Dataset/Polls/2017_poll_results.csv")
df_pl_2018 = pd.read_csv("./Kaggle_Dataset/Polls/2018_poll_results.csv")
df_pl_2019 = pd.read_csv("./Kaggle_Dataset/Polls/2019_poll_results.csv")
df_pl_2021 = pd.read_csv("./Kaggle_Dataset/Polls/2021_poll_results.csv")
df_pl_2022 = pd.read_csv("./Kaggle_Dataset/Polls/2022_poll_results.csv")
df_pl_2023 = pd.read_csv("./Kaggle_Dataset/Polls/2023_poll_results.csv")

In [53]:
years = [2016, 2017, 2018, 2019, 2021, 2022, 2023]
dfs = [df_pl_2016, df_pl_2017, df_pl_2018, df_pl_2019, df_pl_2021, df_pl_2022, df_pl_2023]

dfs_fixed = []
for yr, df_year in zip(years, dfs):
    df_year = df_year.copy()
    df_year["Year"] = str(yr) + "F"
    df_year["Poll_Rank"] = df_year["total_points"].rank(
        ascending=False, method="min"
    ).astype(int)
    df_year = df_year.sort_values("Poll_Rank")
    dfs_fixed.append(df_year)

df_pl = pd.concat(dfs_fixed, ignore_index=True)
df_pl = df_pl.rename(columns={'Contestant': 'Country'})

In [54]:
df_pl.head()

,Country,my_eurovision_scoreboard_points,eurovision_world_points,eurojury_jury_points,eurojury_online_points,discord_points,wiwiblogs_points,ogae_points,total_points,Year,Poll_Rank
0,Australia,115780,4799,284,58,3181,NaN,280,124382,2016F,1
1,Russia,104296,13468,146,80,2404,NaN,392,120786,2016F,2
2,Bulgaria,112538,1866,57,167,3741,NaN,175,118544,2016F,3
3,Ukraine,99503,13057,120,143,5280,NaN,88,118191,2016F,4
4,Armenia,90195,3014,44,64,3309,NaN,13,96639,2016F,5

In [55]:
manual_overrides = {
    "Czechia": "Czech Republic",
}

In [56]:
df_results_modified["Country"] = df_results_modified["Country"].replace(manual_overrides)

In [57]:
# Build mapping from df_results country names → df_pl country names
def fuzzy_map(source_countries, target_countries, threshold=80):
    mapping = {}
    for country in source_countries:
        match, score, _ = process.extractOne(
            country, target_countries, scorer=fuzz.token_sort_ratio
        )
        mapping[country] = match if score >= threshold else country
    return mapping

mapping = fuzzy_map(
    df_results_modified["Country"].unique(),
    df_pl["Country"].unique()
)

In [58]:
for orig, mapped in mapping.items():
    if orig != mapped:
        print(f"{orig!r:30} → {mapped!r}")

In [59]:
# Apply then merge
df_results_modified["Country"] = df_results_modified["Country"].map(mapping)

In [60]:
print(df_results_modified["Country"].unique())

['Ukraine' 'Australia' 'Russia' 'Bulgaria' 'Sweden' 'France' 'Armenia'
 'Poland' 'Lithuania' 'Belgium' 'Netherlands' 'Malta' 'Austria' 'Israel'
 'Latvia' 'Italy' 'Azerbaijan' 'Serbia' 'Hungary' 'Georgia' 'Cyprus'
 'Spain' 'Croatia' 'United Kingdom' 'Czech Republic' 'Germany' 'Portugal'
 'Moldova' 'Romania' 'Norway' 'Belarus' 'Greece' 'Denmark' 'Estonia'
 'Albania' 'Ireland' 'Slovenia' 'Finland' 'Switzerland' 'North Macedonia'
 'Iceland' 'San Marino']

In [61]:
print(df_pl["Country"].unique())

['Australia' 'Russia' 'Bulgaria' 'Ukraine' 'Armenia' 'France' 'Spain'
 'Hungary' 'Latvia' 'Italy' 'Austria' 'Belgium' 'Poland' 'Croatia'
 'Czech Republic' 'Azerbaijan' 'Iceland' 'Sweden' 'Malta' 'Serbia'
 'Cyprus' 'Norway' 'Lithuania' 'Israel' 'Netherlands' 'Germany' 'Estonia'
 'Georgia' 'Belarus' 'Denmark' 'Bosnia and Herzegovina' 'United Kingdom'
 'Albania' 'North Macedonia' 'Moldova' 'Switzerland' 'Finland' 'Greece'
 'Ireland' 'Slovenia' 'San Marino' 'Montenegro' 'Portugal' 'Romania']

In [62]:

df_results_modified = pd.merge(
    df_pl[['Country', 'Poll_Rank', 'Year']],
    df_results_modified[[
        "Place", "Place_Jury", "Place_Televote", "Place_Diff",
        "Country", "Song", "Performer", "Year"
    ]],
    on=['Country', 'Year'],
    how='left'
)

# Sanity check — these should all have matched
print(df_results_modified[df_results_modified["Place"].isna()])

        Country  Poll_Rank   Year  Place  Place_Jury  Place_Televote  \
16      Iceland         17  2016F    NaN         NaN             NaN
21       Norway         22  2016F    NaN         NaN             NaN
26      Estonia         27  2016F    NaN         NaN             NaN
28      Belarus         29  2016F    NaN         NaN             NaN
29      Denmark         30  2016F    NaN         NaN             NaN
..          ...        ...    ...    ...         ...             ...
279     Ireland         33  2023F    NaN         NaN             NaN
280      Greece         34  2023F    NaN         NaN             NaN
281  Azerbaijan         35  2023F    NaN         NaN             NaN
282     Romania         36  2023F    NaN         NaN             NaN
283  San Marino         37  2023F    NaN         NaN             NaN

     Place_Diff Song Performer
16          NaN  NaN       NaN
21          NaN  NaN       NaN
26          NaN  NaN       NaN
28          NaN  NaN       NaN
29          NaN  NaN       NaN
..          ...  ...       ...
279         NaN  NaN       NaN
280         NaN  NaN       NaN
281         NaN  NaN       NaN
282         NaN  NaN       NaN
283         NaN  NaN       NaN

[103 rows x 9 columns]

In [64]:
print(df_results_modified[df_results_modified["Country"]=="Czech Republic"])

            Country  Poll_Rank   Year  Place  Place_Jury  Place_Televote  \
14   Czech Republic         15  2016F   25.0        21.0            26.0
77   Czech Republic         36  2017F    NaN         NaN             NaN
88   Czech Republic          5  2018F    6.0        15.0             4.0
146  Czech Republic         20  2019F   11.0         8.0            24.0
198  Czech Republic         31  2021F    NaN         NaN             NaN
219  Czech Republic         13  2022F   22.0        19.0            22.0
254  Czech Republic          8  2023F   10.0        10.0            17.0

     Place_Diff                Song           Performer
14          5.0             I Stand  Gabriela Gunčíková
77          NaN                 NaN                 NaN
88         11.0           Lie To Me       Mikolas Josef
146        16.0  Friend of a Friend         Lake Malawi
198         NaN                 NaN                 NaN
219         3.0          Lights Off         We Are Domi
254         7.0   My Sister's Crown               Vesna

In [65]:
df_results_modified = pd.merge(
    df_pl[['Country', 'Poll_Rank', 'Year']], 
    df_results_modified[[
        "Place", "Place_Jury", "Place_Televote", "Place_Diff",
        "Country", "Song", "Performer", "Year"
    ]], 
    on=['Country', 'Year'], 
    how='left'   # <- keep all countries from the left (poll) dataframe
)

In [67]:
df_results_modified[df_results_modified["Year"]=="2016F"].sort_values("Place_Televote")

,Country,Poll_Rank,Year,Place,Place_Jury,Place_Televote,Place_Diff,Song,Performer
1,Russia,2,2016F,3.0,5.0,1.0,4.0,You Are The Only One,Sergey Lazarev
3,Ukraine,4,2016F,1.0,2.0,2.0,0.0,1944,Jamala
12,Poland,13,2016F,8.0,25.0,3.0,22.0,Color Of Your Life,Michał Szpak
0,Australia,1,2016F,2.0,1.0,4.0,3.0,Sound Of Silence,Dami Im
2,Bulgaria,3,2016F,4.0,7.0,5.0,2.0,If Love Was A Crime,Poli Genova
17,Sweden,18,2016F,5.0,9.0,6.0,3.0,If I Were Sorry,Frans
4,Armenia,5,2016F,7.0,10.0,7.0,3.0,LoveWave,Iveta Mukuchyan
10,Austria,11,2016F,13.0,24.0,8.0,16.0,Loin d'ici,ZOË
5,France,6,2016F,6.0,3.0,9.0,6.0,J'ai cherché,Amir
22,Lithuania,23,2016F,9.0,12.0,10.0,2.0,I've Been Waiting For This Night,Donny Montell
19,Serbia,20,2016F,18.0,23.0,11.0,12.0,Goodbye (Shelter),Sanja Vučić ZAA
15,Azerbaijan,16,2016F,17.0,19.0,12.0,7.0,Miracle,Samra
8,Latvia,9,2016F,15.0,15.0,13.0,2.0,Heartbeat,Justs
7,Hungary,8,2016F,19.0,18.0,14.0,4.0,Pioneer,Freddie
20,Cyprus,21,2016F,21.0,20.0,15.0,5.0,Alter Ego,Minus One
11,Belgium,12,2016F,10.0,5.0,16.0,11.0,What's The Pressure,Laura Tesoro
24,Netherlands,25,2016F,11.0,11.0,17.0,6.0,Slow Down,Douwe Bob
9,Italy,10,2016F,16.0,13.0,18.0,5.0,No Degree Of Separation,Francesca Michielin
13,Croatia,14,2016F,23.0,22.0,19.0,3.0,Lighthouse,Nina Kraljić
27,Georgia,28,2016F,20.0,14.0,20.0,6.0,Midnight Gold,Nika Kocharov and Young Georgian Lolitaz
18,Malta,19,2016F,12.0,4.0,21.0,17.0,Walk On Walter,Ira Losco
23,Israel,24,2016F,14.0,8.0,22.0,14.0,Made Of Stars,Hovi Star
6,Spain,7,2016F,22.0,16.0,23.0,7.0,Say Yay!,Barei
25,Germany,26,2016F,26.0,26.0,23.0,3.0,Ghost,Jamie-Lee
31,United Kingdom,32,2016F,24.0,17.0,25.0,8.0,You're Not Alone,Joe and Jake
14,Czech Republic,15,2016F,25.0,21.0,26.0,5.0,I Stand,Gabriela Gunčíková
16,Iceland,17,2016F,NaN,NaN,NaN,NaN,NaN,NaN
21,Norway,22,2016F,NaN,NaN,NaN,NaN,NaN,NaN
26,Estonia,27,2016F,NaN,NaN,NaN,NaN,NaN,NaN
28,Belarus,29,2016F,NaN,NaN,NaN,NaN,NaN,NaN
29,Denmark,30,2016F,NaN,NaN,NaN,NaN,NaN,NaN
30,Bosnia and Herzegovina,31,2016F,NaN,NaN,NaN,NaN,NaN,NaN
32,Albania,33,2016F,NaN,NaN,NaN,NaN,NaN,NaN
33,North Macedonia,34,2016F,NaN,NaN,NaN,NaN,NaN,NaN
34,Moldova,35,2016F,NaN,NaN,NaN,NaN,NaN,NaN
35,Switzerland,36,2016F,NaN,NaN,NaN,NaN,NaN,NaN
36,Finland,37,2016F,NaN,NaN,NaN,NaN,NaN,NaN
37,Greece,38,2016F,NaN,NaN,NaN,NaN,NaN,NaN
38,Ireland,39,2016F,NaN,NaN,NaN,NaN,NaN,NaN
39,Slovenia,40,2016F,NaN,NaN,NaN,NaN,NaN,NaN
40,San Marino,41,2016F,NaN,NaN,NaN,NaN,NaN,NaN
41,Montenegro,42,2016F,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
df_results_modified.head()

,Country,Poll_Rank,Year,Place,Place_Jury,Place_Televote,Place_Diff,Song,Performer
0,Australia,1,2016F,2.0,1.0,4.0,3.0,Sound Of Silence,Dami Im
1,Russia,2,2016F,3.0,5.0,1.0,4.0,You Are The Only One,Sergey Lazarev
2,Bulgaria,3,2016F,4.0,7.0,5.0,2.0,If Love Was A Crime,Poli Genova
3,Ukraine,4,2016F,1.0,2.0,2.0,0.0,1944,Jamala
4,Armenia,5,2016F,7.0,10.0,7.0,3.0,LoveWave,Iveta Mukuchyan

In [69]:
df_results_modified = df_results_modified.sort_values(by=['Year', 'Place'])

In [70]:
df_results_modified.head()

,Country,Poll_Rank,Year,Place,Place_Jury,Place_Televote,Place_Diff,Song,Performer
3,Ukraine,4,2016F,1.0,2.0,2.0,0.0,1944,Jamala
0,Australia,1,2016F,2.0,1.0,4.0,3.0,Sound Of Silence,Dami Im
1,Russia,2,2016F,3.0,5.0,1.0,4.0,You Are The Only One,Sergey Lazarev
2,Bulgaria,3,2016F,4.0,7.0,5.0,2.0,If Love Was A Crime,Poli Genova
17,Sweden,18,2016F,5.0,9.0,6.0,3.0,If I Were Sorry,Frans

In [71]:
df_results_modified['Bubble_Size'] = df_results_modified['Place'].max() - df_results_modified['Place'] + 1

In [72]:
df_results_modified['Year_as_format'] = (
    df_results_modified['Year']
        .str.replace('F', '', regex=False)  # remove 'F'
        .astype(int)                        # convert to integer
)

In [73]:
df_results_modified['Year_as_format'] = pd.to_datetime(
    df_results_modified['Year_as_format'], format='%Y'
)

In [74]:
colors = ['#00429d', '#1348a0', '#1f4ea3', '#2854a6', '#305ba9', '#3761ab', '#3e67ae', '#446eb1', '#4a74b4', '#507bb7', '#5681b9', '#5c88bc', '#618fbf', '#6795c1', '#6d9cc4', '#73a2c6', '#79a9c9', '#7fb0cb', '#85b7ce', '#8cbdd0', '#93c4d2', '#9acbd5', '#a1d1d7', '#a9d8d9', '#b1dfdb', '#b9e5dd', '#c3ebde', '#cdf1e0', '#daf7e1', '#e8fce1', '#fcf9d7', '#f9f2ce', '#f5ecc6', '#f2e6bd', '#eedfb5', '#ebd9ad', '#e7d3a5', '#e4cd9e', '#e0c796', '#dcc08f', '#d8ba88', '#d4b482', '#d0ae7b', '#cca875', '#c8a26f', '#c39c6a', '#bf9764', '#bb9160', '#b68b5b', '#b28557', '#ae7f54', '#a97950', '#a5744e', '#a06e4c', '#9b684b', '#97624b', '#925d4c', '#8c574f', '#875153', '#814c5a']

countries = ['Ukraine', 'Australia', 'Russia', 'Bulgaria', 'Sweden', 'France',
       'Armenia', 'Poland', 'Lithuania', 'Belgium', 'Netherlands',
       'Malta', 'Austria', 'Israel', 'Latvia', 'Italy', 'Azerbaijan',
       'Serbia', 'Hungary', 'Georgia', 'Cyprus', 'Spain', 'Croatia',
       'United Kingdom', 'Germany', 'Ireland', 'Greece', 'Norway',
       'Denmark', 'Albania', 'Czech Republic', 'Bosnia and Herzegovina',
       'Iceland', 'Estonia', 'Finland', 'North Macedonia', 'Slovenia',
       'Switzerland', 'Belarus', 'San Marino', 'Moldova', 'Montenegro',
       'Portugal', 'Romania']

# Create dictionary mapping country -> color
country_colors = dict(zip(countries, colors))

In [75]:
import matplotlib.colors as mcolors
def fade_color(hex_color, rank, max_rank):
    """
    Returns a lighter color depending on rank.
    Rank 1 = full color, rank=max_rank = very light.
    """
    # Convert hex to RGB (0-1)
    rgb = mcolors.to_rgb(hex_color)
    
    # Calculate fade factor: rank 1 = 1, rank=max_rank = 0.3 (adjustable)
    min_strength = 0.2
    strength = 1
    
    # Apply strength
    faded_rgb = tuple([c * strength for c in rgb])
    
    # Convert back to hex
    return mcolors.to_hex(faded_rgb)

In [76]:
max_rank = df_results_modified['Place'].max()

df_results_modified['Color'] = df_results_modified.apply(
    lambda row: fade_color(country_colors[row['Country']], row['Place'], max_rank),
    axis=1
)

In [77]:
df_results_modified.head()

,Country,Poll_Rank,Year,Place,Place_Jury,Place_Televote,Place_Diff,Song,Performer,Bubble_Size,Year_as_format,Color
3,Ukraine,4,2016F,1.0,2.0,2.0,0.0,1944,Jamala,26.0,2016-01-01,#00429d
0,Australia,1,2016F,2.0,1.0,4.0,3.0,Sound Of Silence,Dami Im,25.0,2016-01-01,#1348a0
1,Russia,2,2016F,3.0,5.0,1.0,4.0,You Are The Only One,Sergey Lazarev,24.0,2016-01-01,#1f4ea3
2,Bulgaria,3,2016F,4.0,7.0,5.0,2.0,If Love Was A Crime,Poli Genova,23.0,2016-01-01,#2854a6
17,Sweden,18,2016F,5.0,9.0,6.0,3.0,If I Were Sorry,Frans,22.0,2016-01-01,#305ba9

In [87]:
df_results_modified["agreement_score"] = df_results_modified.groupby("Year", group_keys=False).apply(
    lambda g: 1 - abs(g["Poll_Rank"] - g["Place_Televote"]) / (len(g) - 1)
)

C:\Users\mutua\AppData\Local\Temp\ipykernel_28700\433970495.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_results_modified["agreement_score"] = df_results_modified.groupby("Year", group_keys=False).apply(

In [88]:
df_results_modified.head()

,Country,Poll_Rank,Year,Place,Place_Jury,Place_Televote,Place_Diff,Song,Performer,Bubble_Size,Year_as_format,Color,agreement_score,spearman_per_year,spearman_per_country
0,Ukraine,4,2016F,1.0,2.0,2.0,0.0,1944,Jamala,26.0,2016-01-01,#00429d,0.951220,0.584274,0.808824
1,Australia,1,2016F,2.0,1.0,4.0,3.0,Sound Of Silence,Dami Im,25.0,2016-01-01,#1348a0,0.926829,0.584274,0.273230
2,Russia,2,2016F,3.0,5.0,1.0,4.0,You Are The Only One,Sergey Lazarev,24.0,2016-01-01,#1f4ea3,0.975610,0.584274,0.866025
3,Bulgaria,3,2016F,4.0,7.0,5.0,2.0,If Love Was A Crime,Poli Genova,23.0,2016-01-01,#2854a6,0.951220,0.584274,0.632456
4,Sweden,18,2016F,5.0,9.0,6.0,3.0,If I Were Sorry,Frans,22.0,2016-01-01,#305ba9,0.707317,0.584274,0.878850

In [ ]:
from scipy.stats import spearmanr
spearman_per_year_place_poll = (
    df_results_modified.groupby("Year", group_keys=False)[["Place", "Poll_Rank"]]
      .apply(lambda x: spearmanr(x["Place"], x["Poll_Rank"], nan_policy='omit').correlation)
      .reset_index(name="Agreement_Score")
)

In [ ]:
spearman_per_year_place_poll

    Year  Agreement_Score
0  2016F         0.584274
1  2017F         0.755897
2  2018F         0.577436
3  2019F         0.772308
4  2021F         0.770940
5  2022F         0.719231
6  2023F         0.269060

In [94]:
spearman_per_year_public_poll = (
    df_results_modified.groupby("Year", group_keys=False)[["Poll_Rank", "Place_Televote"]]
      .apply(lambda x: spearmanr(x["Poll_Rank"], x["Place_Televote"], nan_policy='omit').correlation)
      .reset_index(name="Agreement_Score"))

In [95]:
spearman_per_year_public_poll

    Year  Agreement_Score
0  2016F         0.620961
1  2017F         0.679207
2  2018F         0.456410
3  2019F         0.634188
4  2021F         0.735385
5  2022F         0.624615
6  2023F         0.040684

In [ ]:
def spearman_safe(x):
    x = x.dropna(subset=["Poll_Rank", "Place"])  # remove rows with NA
    if len(x) < 3:
        return None  # or np.nan
    return spearmanr(x["Poll_Rank"], x["Place"]).correlation

spearman_per_country = (
    df_results_modified.groupby("Country")[["Poll_Rank", "Place"]]
    .apply(spearman_safe)
    .reset_index(name="Agreement_Score")
)

In [83]:
spearman_per_country.head()

      Country  Agreement_Score
0     Albania         0.800000
1     Armenia         1.000000
2   Australia         0.273230
3     Austria         0.316228
4  Azerbaijan         0.500000

In [84]:
#match per year
df_results_modified = df_results_modified.merge(
    spearman_per_year,
    on="Year",
    how="left"
)
#match per country
df_results_modified = df_results_modified.merge(
    spearman_per_country,
    on="Country",
    how="left",
    suffixes=("", "_country")
)

In [85]:
df_results_modified.rename(
    columns={"Agreement_Score": "spearman_per_year", "Agreement_Score_country": "spearman_per_country"},
    inplace=True
)

In [86]:
df_results_modified.head()

,Country,Poll_Rank,Year,Place,Place_Jury,Place_Televote,Place_Diff,Song,Performer,Bubble_Size,Year_as_format,Color,agreement_score,spearman_per_year,spearman_per_country
0,Ukraine,4,2016F,1.0,2.0,2.0,0.0,1944,Jamala,26.0,2016-01-01,#00429d,0.992933,0.584274,0.808824
1,Australia,1,2016F,2.0,1.0,4.0,3.0,Sound Of Silence,Dami Im,25.0,2016-01-01,#1348a0,0.989399,0.584274,0.273230
2,Russia,2,2016F,3.0,5.0,1.0,4.0,You Are The Only One,Sergey Lazarev,24.0,2016-01-01,#1f4ea3,0.996466,0.584274,0.866025
3,Bulgaria,3,2016F,4.0,7.0,5.0,2.0,If Love Was A Crime,Poli Genova,23.0,2016-01-01,#2854a6,0.992933,0.584274,0.632456
4,Sweden,18,2016F,5.0,9.0,6.0,3.0,If I Were Sorry,Frans,22.0,2016-01-01,#305ba9,0.957597,0.584274,0.878850

In [96]:
df_results_modified["rank_difference"] = df_results_modified["Poll_Rank"] - df_results_modified["Place_Televote"]

In [97]:
df_results_modified.to_csv("eurovision_results4.csv", index=False)

In [98]:
df_results[df_results["Year"]=="2022F"].head()

,Place,Place_Jury,Place_Televote,Place_Diff,Points,Points_Jury,Points_Televote,Points_Diff,Flag,Country,Performer,Song,Qualification,Composer,Writer,Year
77,1,4,1,3,631,192,439,247,NaN,Ukraine,Kalush Orchestra,Stefania,NaN,"Ihor Didenchuk, Tymofii Muzychuk, Vitalii Duzhyk","Ivan Klymenko, Oleh Psiuk",2022F
78,2,1,5,4,466,283,183,100,NaN,United Kingdom,Sam Ryder,SPACE MAN,NaN,"Sam Ryder, Amy Wadge, Max Wolfgang","Sam Ryder, Amy Wadge, Max Wolfgang",2022F
79,3,3,3,0,459,231,228,3,NaN,Spain,Chanel,SloMo,NaN,"Arjen Thonen, Ibere Fortes, Keith Harris, Lero...","Ibere Fortes, Leroy Sánchez, Maggie Szabo",2022F
80,4,2,6,4,438,258,180,78,NaN,Sweden,Cornelia Jakobs,Hold Me Closer,NaN,"Cornelia Jakobs, David Zandén, Isa Molin","Cornelia Jakobs, David Zandén, Isa Molin",2022F
81,5,11,4,7,312,87,225,138,NaN,Serbia,Konstrakta,In Corpore Sano,NaN,"Ana Đurić, Milovan Bošković",Ana Đurić,2022F

In [ ]:
df_jr_2016.head()

In [ ]:
df_results_temp = df_results[df_results["Year"]=="2016F"]
df_jr_2016_temp = df_jr_2016.rename(columns={"Contestant": "Country"})

df_merge = pd.merge(
    df_jr_2016_temp[['Country', 'Jury score']], 
    df_results_temp[['Country', 'Points']], 
    on='Country', 
    how='inner'
)

df_merge = df_merge.sort_values(by='Points')

plt.figure(figsize=(10,6), facecolor='black')
ax = plt.gca()  # get current axes
ax.set_facecolor('black')  # plot area background

# Example plot
ax.plot(df_merge['Country'], df_merge['Jury score'], marker='o', color='cyan', label='Jury Score')
ax.plot(df_merge['Country'], df_merge['Points'], marker='x', color='magenta', label='Total Score')

ax.set_xticks(range(len(df_merge['Country'])))
ax.set_xticklabels(df_merge['Country'], rotation=90, color='white')
ax.tick_params(axis='x', colors='white')
ax.set_ylabel("Points", color='white')
ax.tick_params(axis='y', colors='white')
ax.set_title("Eurovision 2016: Jury vs Total Points", color='white')

for spine in ax.spines.values():
    spine.set_edgecolor('white')

ax.legend(facecolor='gray', edgecolor='white', labelcolor='white')
plt.tight_layout()
plt.show()

In [ ]:
df_jr_2016 = df_jr_2016.rename(columns={"Contestant": "Country"})
df_jr_2017 = df_jr_2017.rename(columns={"Contestant": "Country"})
df_jr_2018 = df_jr_2018.rename(columns={"Contestant": "Country"})
df_jr_2019 = df_jr_2019.rename(columns={"Contestant": "Country"})
df_jr_2021 = df_jr_2021.rename(columns={"Contestant": "Country"})
df_jr_2022 = df_jr_2022.rename(columns={"Contestant": "Country"})
df_jr_2023 = df_jr_2023.rename(columns={"Contestant": "Country"})

In [ ]:
df_results_temp = df_results[df_results["Year"]=="2016F"]
df_merge_2016_jury = pd.merge(
    df_jr_2016[['Country', 'Jury score']], 
    df_results_temp[['Country', 'Points']], 
    on='Country', 
    how='inner'
)

df_merge_2016_televote = pd.merge(
    df_jr_2016[['Country', 'Televoting score']], 
    df_results_temp[['Country', 'Points']], 
    on='Country', 
    how='inner'
)

df_merge_2016 = pd.merge(
    df_jr_2016[['Country', 'Jury score', 'Televoting score']], 
    df_results_temp[['Country', 'Place', 'Points', "Place_Televote"]], 
    on='Country', 
    how='inner'
)

In [ ]:

df_merge_2016 = df_merge_2016.sort_values(by='Place')

In [ ]:
df_pl_2016["Place"] = df_pl_2016["total_points"].rank(
    ascending=False,
    method="min"
).astype(int)

In [ ]:
df_pl_2016 = df_pl_2016.sort_values(by='total_points', ascending=False).rename(columns={"Contestant": "Country"})

In [ ]:
df_pl_2016.head()

In [ ]:
plt.figure(figsize=(10,6), facecolor='black')
ax = plt.gca()  # get current axes
ax.set_facecolor('black')  # plot area background

# Example plot
ax.plot(df_merge_2016['Country'], df_merge_2016['Jury score'], marker='o', color='cyan', label='Jury Score')
ax.plot(df_merge_2016['Country'], df_merge_2016['Points'], marker='x', color='magenta', label='Total Score')

ax.set_xticks(range(len(df_merge_2016['Country'])))
ax.set_xticklabels(df_merge_2016['Country'], rotation=90, color='white')
ax.tick_params(axis='x', colors='white')
ax.set_ylabel("Points", color='white')
ax.tick_params(axis='y', colors='white')
ax.set_title("Eurovision 2016: Jury vs Total Points", color='white')

for spine in ax.spines.values():
    spine.set_edgecolor('white')

ax.legend(facecolor='gray', edgecolor='white', labelcolor='white')
plt.tight_layout()
plt.show()

In [ ]:
df_jr_2016.head(5)

In [ ]:
df_results[df_results["Year"] == "2016F"].head(5)

In [ ]:
df_merge_2016.head(5)

In [ ]:
df_plmerge_2016 = pd.merge(
    df_pl_2016[['Country', "Place"]], 
    df_merge_2016[['Country', 'Place', 'Points', "Place_Televote"]], 
    on='Country', 
    how='inner'
)

In [ ]:
df_plmerge_2016 = df_plmerge_2016.rename(columns={"Place_x": "Pool Placing", "Place_y": "Place"})

In [ ]:
df_plmerge_2016.head(5)

In [ ]:
import plotly.express as px

fig = px.scatter(
    df_plmerge_2016,
    x="Pool Placing",
    y="Place",
    color="Place_Televote",
    color_continuous_scale="Viridis",
    trendline="ols"
)

fig.update_layout(
    title="Poll vs Final Ranking (Color = Televote Rank)",
    xaxis_title="Poll Rank",
    yaxis_title="Final Rank"
)

fig.show()

In [ ]:
import plotly.graph_objects as go

fig = go.Figure()

df_results_tmp = df_results[df_results["Year"]=="2016F"]

for i in range(len(df_results_tmp)):
    fig.add_trace(go.Scatter(
        x=["Televote", "Final"],
        y=[df_results_tmp["Place_Televote"].iloc[i], df_results_tmp["Place"].iloc[i]],
        mode="lines+markers",
        line=dict(width=2),
        name=df_results_tmp["Country"].iloc[i]
    ))

fig.update_layout(
    title="Impact of Jury on Final Ranking",
    yaxis_title="Rank (Lower is Better)",
    yaxis_autorange="reversed"
)

fig.show()

In [ ]:
df_results_tmp["jury_impact"] = df_results_tmp["Place_Jury"] - df_results_tmp["Place"]
df_results_tmp["abs_impact"] = df_results_tmp["jury_impact"].abs()

In [ ]:
top_shifts = df_results_tmp.sort_values("abs_impact", ascending=False).head(10)

fig1 = px.bar(
    top_shifts,
    x="Country",
    y="jury_impact",
    color="jury_impact",
    color_continuous_scale="RdBu",
    title="Largest Jury Impact on Final Placement"
)

fig1.update_layout(
    yaxis_title="Placement Change (Televote - Final)"
)

fig1.show()

In [ ]:
top10 = df_results_tmp[df_results_tmp["Place"] <= 10].copy()

In [ ]:
top10["televote_only_rank"] = top10["Place_Televote"]

In [ ]:
fig2 = px.scatter(
    top10,
    x="Place_Televote",
    y="Place",
    text="Country",
    title="Jury Influence on Top 10 Placements"
)

fig2.update_traces(textposition="top center")

fig2.update_layout(
    xaxis_title="Televote Rank",
    yaxis_title="Final Rank",
    yaxis_autorange="reversed",
    xaxis_autorange="reversed"
)

fig2.show()

In [ ]:
df_results.head()

In [ ]:
df_jr_2016 = df_jr_2016.rename(columns={"Contestant": "Country"})
df_jr_2017 = df_jr_2017.rename(columns={"Contestant": "Country"})
df_jr_2018 = df_jr_2018.rename(columns={"Contestant": "Country"})
df_jr_2019 = df_jr_2019.rename(columns={"Contestant": "Country"})
df_jr_2021 = df_jr_2021.rename(columns={"Contestant": "Country"})
df_jr_2022 = df_jr_2022.rename(columns={"Contestant": "Country"})
df_jr_2023 = df_jr_2023.rename(columns={"Contestant": "Country"})

In [ ]:
df_pl_2016.head()

In [ ]:
years = [2016, 2017, 2018, 2019, 2021, 2022, 2023]
dfs = [df_pl_2016, df_pl_2017, df_pl_2018, df_pl_2019, df_pl_2021, df_pl_2022, df_pl_2023]

for yr, df_year in zip(years, dfs):
    df_year["Year"] = str(yr) + "F"
    # Compute Poll_Rank per year
    df_year["Poll_Rank"] = df_year["total_points"].rank(
        ascending=False,
        method="min"
    ).astype(int)
    df_year = df_year.sort_values("Poll_Rank")

# Concatenate all years
df_pl = pd.concat(dfs, ignore_index=True)
df_pl = df_pl.rename(columns={'Contestant':'Country'})

In [ ]:
df_pl

In [ ]:

# Merge with results
df = pd.merge(
    df_results[['Country', 'Place_Televote', 'Year', 'Place']],
    df_pl[['Country', 'Poll_Rank', 'Year', 'total_points']],
    left_on=['Country', 'Year'],
    right_on=['Country', 'Year'],
    how='inner'
)

In [ ]:
df.head()

In [ ]:
# Optional: rename total_points
df.rename(columns={'total_points': 'Poll Points'}, inplace=True)

In [ ]:
df[df["Year"]=="2016F"].head()

In [ ]:
import plotly.graph_objects as go
import pandas as pd
from scipy.stats import spearmanr

# Assume df is loaded with 'year', 'country', 'Poll_Rank', 'Place_Televote', 'Place'

# Compute errors
df["poll_error"] = (df["Poll_Rank"] - df["Place"]).abs()
df["televote_error"] = (df["Place_Televote"] - df["Place"]).abs()
df["jury_shift"] = (df["Place_Televote"] - df["Place"]).abs()

years = sorted(df['Year'].unique())
views = ["Full Field", "Top 10"]

In [ ]:

# Create figure
fig1 = go.Figure()

trace_registry = []

for year in ["All"] + years:
    for view in views:
        data = df.copy()
        if year != "All":
            data = data[data['Year'] == year]
        if view == "Top 10":
            data = data[data['Place'] <= 10]

        trace = go.Scatter(
            x=data["poll_error"],
            y=data["televote_error"],
            mode="markers",
            marker=dict(
                color=data["jury_shift"],
                colorscale="Cividis",
                size=8,
                opacity=0.8,
                showscale=False
            ),
            text=data["Country"],
            hovertemplate="<b>%{text}</b><br>Poll Error: %{x}<br>Televote Error: %{y}<extra></extra>",
            visible=False
        )

        fig1.add_trace(trace)
        trace_registry.append((year, view))

# Diagonal reference line
fig1.add_shape(type="line", x0=0, y0=0, x1=df["poll_error"].max(), y1=df["poll_error"].max(),
               line=dict(dash="dash", color="black"))

# Dropdown buttons
buttons = []
for year in ["All"] + years:
    for view in views:
        visible = [(ty == year and tv == view) for ty, tv in trace_registry]
        buttons.append(dict(
            label=f"{year} — {view}",
            method="update",
            args=[{"visible": visible}]
        ))

fig1.update_layout(
    updatemenus=[dict(buttons=buttons, x=1.05, y=1.1)],
    title="Prediction Accuracy: Poll vs Televote",
    xaxis_title="Poll Deviation from Final",
    yaxis_title="Televote Deviation from Final",
    plot_bgcolor="#F5F5F2",
    paper_bgcolor="#F5F5F2"
)

# Compute initial stats overlay (All + Full Field)
base_data = df.copy()
corr_poll, _ = spearmanr(base_data["Poll_Rank"], base_data["Place"])
corr_tele, _ = spearmanr(base_data["Place_Televote"], base_data["Place"])
mean_poll_error = base_data["poll_error"].mean()
mean_televote_error = base_data["televote_error"].mean()

fig1.add_annotation(
    x=0.02, y=0.98, xref="paper", yref="paper",
    text=f"<b>Stats (All Years, Full Field)</b><br>Spearman ρ Poll vs Final: {corr_poll:.2f}<br>"
         f"Spearman ρ Televote vs Final: {corr_tele:.2f}<br>"
         f"Mean Poll Error: {mean_poll_error:.2f}<br>"
         f"Mean Televote Error: {mean_televote_error:.2f}",
    showarrow=False,
    bordercolor="black", borderwidth=1,
    bgcolor="white", align="left"
)

fig1.show()

In [ ]:
# Compute jury effect
df["jury_effect"] = df["Place"] - df["Place_Televote"]

fig2 = go.Figure()
trace_registry2 = []

for year in ["All"] + years:
    for view in views:
        data = df.copy()
        if year != "All":
            data = data[data['Year'] == year]
        if view == "Top 10":
            data = data[data['Place'] <= 10]

        trace = go.Violin(
            x=data["jury_effect"],
            box_visible=True,
            meanline_visible=True,
            opacity=0.75,
            line_color="#0072B2",
            visible=False,
            points="all"
        )
        fig2.add_trace(trace)
        trace_registry2.append((year, view))

# Zero line reference
fig2.add_vline(x=0, line_dash="dash", line_color="black")

# Dropdown buttons
buttons2 = []
for year in ["All"] + years:
    for view in views:
        visible = [(ty == year and tv == view) for ty, tv in trace_registry2]
        buttons2.append(dict(
            label=f"{year} — {view}",
            method="update",
            args=[{"visible": visible}]
        ))

fig2.update_layout(
    updatemenus=[dict(buttons=buttons2, x=1.05, y=1.1)],
    title="Jury Intervention Distribution",
    xaxis_title="Jury Effect (Final − Televote Rank)",
    plot_bgcolor="#F5F5F2",
    paper_bgcolor="#F5F5F2",
    showlegend=False
)

# Initial stats overlay (All + Full Field)
base_data = df.copy()
mean_shift = base_data["jury_effect"].mean()
max_shift = base_data["jury_effect"].abs().max()

fig2.add_annotation(
    x=0.02, y=0.98, xref="paper", yref="paper",
    text=f"<b>Stats (All Years, Full Field)</b><br>"
         f"Mean Jury Shift: {mean_shift:.2f} places<br>"
         f"Maximum Jury Shift: {max_shift} places",
    showarrow=False,
    bordercolor="black", borderwidth=1,
    bgcolor="white", align="left"
)

fig2.show()

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.colors as pc
import numpy as np
import pandas as pd

# df_top10: your dataframe with all years, only top 10 final placements per year
df_top10 = df[df['Place'] <= 10].copy()
df_top10['JuryEffect'] = df_top10['Place'] - df_top10['Place_Televote']

# Normalize JuryEffect for coloring
max_shift = df_top10['JuryEffect'].abs().max()
df_top10['ColorNorm'] = (df_top10['JuryEffect'] + max_shift) / (2*max_shift)

# Determine top 3 movers per year
df_top10['Highlight'] = df_top10.groupby('Year')['JuryEffect'].transform(
    lambda x: x.abs() >= x.abs().nlargest(3).min()
)

# Apply slight Y jitter for all lines
jitter_strength = 0.1
stages = ['Poll_Rank', 'Place_Televote', 'Place']
for stage in stages:
    df_top10[stage + '_jit'] = df_top10[stage] + np.random.uniform(-jitter_strength, jitter_strength, len(df_top10))

# Create 3-row, 1-column subplots
fig = make_subplots(
    rows=3, cols=1,
    shared_xaxes=False,
    vertical_spacing=0.15,
    subplot_titles=[
        "Poll vs Televote (Poll predicts public vote?)",
        "Televote vs Final (Jury influence)",
        "Poll vs Final (Overall accuracy)"
    ]
)

# Helper to get hex color
def get_hex_color(norm_value):
    return pc.sample_colorscale('Cividis', [norm_value])[0]

# Add lines
for _, row in df_top10.iterrows():
    # Gray background for non-highlighted
    if row['Highlight']:
        line_color = get_hex_color(row['ColorNorm'])
        line_width = 2.5
        show_text = True
    else:
        line_color = "#cccccc"
        line_width = 1
        show_text = False
    
    line_id = f"{row['Country']} ({row['Year']})"
    
    # --- Poll vs Televote ---
    fig.add_trace(go.Scatter(
        x=['Poll', 'Televote'],
        y=[row['Poll_Rank_jit'], row['Place_Televote_jit']],
        mode='lines+markers+text',
        line=dict(color=line_color, width=line_width),
        marker=dict(size=5),
        text=[None, None, row['Country']] if show_text else [None, None, None],
        textposition='top center',
        hovertemplate=(
            f"<b>{row['Country']} ({row['Year']})</b><br>"
            f"Poll: {row['Poll_Rank']}<br>"
            f"Televote: {row['Place_Televote']}<br>"
            f"Jury Effect: {row['JuryEffect']}"
        ),
        name=line_id
    ), row=1, col=1)
    
    # --- Televote vs Final ---
    fig.add_trace(go.Scatter(
        x=['Televote', 'Final'],
        y=[row['Place_Televote_jit'], row['Place_jit']],
        mode='lines+markers+text',
        line=dict(color=line_color, width=line_width),
        marker=dict(size=5),
        text=[None, None, row['Country']] if show_text else [None, None, None],
        textposition='top center',
        hovertemplate=(
            f"<b>{row['Country']} ({row['Year']})</b><br>"
            f"Televote: {row['Place_Televote']}<br>"
            f"Final: {row['Place']}<br>"
            f"Jury Effect: {row['JuryEffect']}"
        ),
        name=line_id
    ), row=2, col=1)
    
    # --- Poll vs Final ---
    fig.add_trace(go.Scatter(
        x=['Poll', 'Final'],
        y=[row['Poll_Rank_jit'], row['Place_jit']],
        mode='lines+markers+text',
        line=dict(color=line_color, width=line_width),
        marker=dict(size=5),
        text=[None, None, row['Country']] if show_text else [None, None, None],
        textposition='top center',
        hovertemplate=(
            f"<b>{row['Country']} ({row['Year']})</b><br>"
            f"Poll: {row['Poll_Rank']}<br>"
            f"Final: {row['Place']}<br>"
            f"Jury Effect: {row['JuryEffect']}"
        ),
        name=line_id
    ), row=3, col=1)

# Reverse Y axes (lower rank = better)
for r in [1,2,3]:
    fig.update_yaxes(autorange='reversed', row=r, col=1)

# Layout
fig.update_layout(
    height=1920, width=1080,
    title="Eurovision Rankings (2016–2023) — Top Jury Movers Highlighted",
    plot_bgcolor="#F5F5F2",
    paper_bgcolor="#F5F5F2",
    showlegend=False
)

fig.show()

In [ ]:
import plotly.colors as pc
import colorsys
import plotly.graph_objects as go
import dash
from dash import Dash, dcc, html, Input, Output, State

# --- Assume df_plot contains the data ---
# Required columns: Country, year, Place (final), Poll_Rank, Place_Televote
df_plot1 = df.copy()
df_plot1['JuryEffect'] = df_plot1['Place'] - df_plot1['Place_Televote']
max_shift = df_plot1['JuryEffect'].abs().max()
df_plot1['AbsEffect'] = df_plot1['JuryEffect'].abs()
max_effect = df_plot1['AbsEffect'].max()

def compute_opacity(df, k=4.0):

    df["NormEffect"] = df.groupby("Country")["AbsEffect"].transform(
        lambda x: (x - x.min()) / (x.max() - x.min() + 1e-9)
    )

    df["Opacity"] = np.exp(-k * (1 - df["NormEffect"]))

    # clamp very small values
    df["Opacity"] = df["Opacity"].clip(lower=0.02)

    return df

strongest_per_country = (
    df_plot1.loc[df_plot1.groupby("Country")["AbsEffect"].idxmax()]
)

global_strongest = df_plot1.loc[df_plot1["AbsEffect"].idxmax()]

# Assign base hue per country from your predefined list
hue_list = [
    "#002471","#4b1b54","#6e001f","#6c006f","#7c005d","#9f0038","#772b9d",
    "#406200","#005ebc","#007d2c","#5d8746","#00966a","#f14793","#e35cc3",
    "#b077f0","#00a6fd","#ff7463","#ff7bb0","#db92cb","#ff96dc","#e6a0ff",
    "#e1ba2f","#3ce88f","#93e164","#cedc71","#c1de91"
]
countries = df_plot1['Country'].unique()
country_color_map = {country: hue_list[i % len(hue_list)] for i, country in enumerate(countries)}

# Function to adjust saturation of hex color
def adjust_saturation(hex_color, factor=1.0):
    r, g, b = [int(hex_color[i:i+2],16)/255 for i in (1,3,5)]
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    s_new = min(max(s*factor, 0.0), 1.0)
    r_new, g_new, b_new = colorsys.hls_to_rgb(h, l, s_new)
    return '#{:02x}{:02x}{:02x}'.format(int(r_new*255), int(g_new*255), int(b_new*255))

# Compute dynamic point color based on JuryEffect magnitude
df_plot1['PointColor'] = df_plot1.apply(
    lambda row: adjust_saturation(country_color_map[row['Country']], factor=1 + abs(row['JuryEffect'])/max_shift),
    axis=1
)

# Compute point size (bigger = more JuryEffect)
df_plot1['PointSize'] = df_plot1['JuryEffect'].abs() * 3 + 6  # tweak scale as needed

# Optional: Y-axis jitter for overlapping placements
jitter_strength = 0.05
df_plot1['Place_jit'] = df_plot1['Place'] + np.random.uniform(-jitter_strength, jitter_strength, len(df_plot1))

In [ ]:
df_plot1.head()

In [ ]:
def fade_to_bg(hex_color, strength, bg="#ffffff"):
    """
    Fade a hex color to the background based on strength (0..1)
    strength=1 -> full color, strength=0 -> background color
    """
    # Convert hex to RGB
    r1, g1, b1 = [int(hex_color[i:i+2],16) for i in (1,3,5)]
    r2, g2, b2 = [int(bg[i:i+2],16) for i in (1,3,5)]
    r = int(r1*strength + r2*(1-strength))
    g = int(g1*strength + g2*(1-strength))
    b = int(b1*strength + b2*(1-strength))
    return f"rgb({r},{g},{b})"

In [ ]:
df_plot1.head()

In [ ]:
def build_figure(selected=None, hovered=None):
    fig = go.Figure()

    # Multiple selection support
    if selected is None:
        selected_countries = []
    elif isinstance(selected, list):
        selected_countries = selected
    else:
        selected_countries = [selected]

    active_country = hovered

    # Loop over countries
    for country in df_plot1["Country"].unique():
        df_country = df_plot1[df_plot1["Country"] == country].sort_values("Year")
        x = df_country["Year"].values
        y = df_country["Place"].values

        # Normalize JuryEffect for fading
        jury_abs = df_country["JuryEffect"].abs()
        jury_min, jury_max = df_plot1["JuryEffect"].abs().min(), df_plot1["JuryEffect"].abs().max()
        jury_norm = (jury_abs - jury_min) / (jury_max - jury_min + 1e-9)

        # Marker color
        marker_colors = [fade_to_bg(c, 0.8*s) for c,s in zip(df_country["PointColor"], jury_norm)]
        if active_country == country or country in selected_countries:
            marker_colors = [fade_to_bg(c, 1.0) for c in df_country["PointColor"]]

        # Marker size = Televote
        tv = df_country["Place_Televote"].values
        marker_sizes = 5 + 15 * (tv / tv.max())

        # Marker border width = Poll
        poll = df_country["Poll_Rank"].values
        border_widths = 1 + 2*(poll / poll.max())

        # Line opacity
        if active_country == country or country in selected_countries:
            line_opacity = 1.0
        else:
            line_opacity = 0.2 if selected_countries or active_country else 0.02
        line_color = f"rgba(0,0,0,{line_opacity})"

        # Add trace
        fig.add_trace(go.Scattergl(
            x=x,
            y=y,
            mode="lines+markers",
            line=dict(color=line_color, width=3),
            marker=dict(
                size=marker_sizes,
                color=marker_colors,
                line=dict(width=border_widths, color="black")
            ),
            hovertext=[
                f"{c}<br>Year: {yr}<br>Place: {p}<br>JuryEffect: {j:.2f}<br>Poll: {pl:.2f}<br>Televote: {tvv:.2f}"
                for c, yr, p, j, pl, tvv in zip(
                    df_country["Country"], df_country["Year"], df_country["Place"],
                    df_country["JuryEffect"], df_country["Poll_Rank"], df_country["Place_Televote"]
                )
            ],
            hoverinfo="text",
            name=country,
            showlegend=False
        ))

    # Layout
    fig.update_layout(
        height=900,
        hovermode="closest",
        template="plotly_white",
        title="Eurovision 2016-2023: Jury / Poll / Televote Effects",
        xaxis=dict(title="Year", dtick=1),
        yaxis=dict(title="Final Place (Lower is Better)", autorange="reversed")
    )

    return fig

In [ ]:
# --- Create Plotly figure ---
fig = go.Figure()

for country in df_plot1['Country'].unique():
    df_country = df_plot1[df_plot1['Country']==country].sort_values('Year')
    years = df_country['Year'].values
    places = df_country['Place'].values
    sizes = df_country['PointSize'].values
    colors = df_country['PointColor'].values
    hover_text = df_country['Country'].values
    custom_data = df_country[['Poll_Rank','Place_Televote','JuryEffect']].values
    opacity = df_country['Opacity'].values

    # --- Split into consecutive year segments ---
    segment_start = 0
    for i in range(1, len(years)+1):
        # If non-consecutive year or end of data
        if i == len(years) or int(years[i][0:-2]) != int(years[i-1][0:-2]):
            seg_years = years[segment_start:i]
            seg_places = places[segment_start:i]
            seg_sizes = sizes[segment_start:i]
            seg_colors = colors[segment_start:i]
            seg_hover = hover_text[segment_start:i]
            seg_custom = custom_data[segment_start:i]
            seg_opacity = opacity[segment_start:i]

            # If single point, just marker
            mode_type = 'markers' if len(seg_years)==1 else 'lines+markers'

            fig.add_trace(go.Scatter(
                x=seg_years,
                y=seg_places,
                mode=mode_type,
                line=dict(color=seg_colors[0], width=2),
                marker=dict(size=seg_sizes, color=seg_colors, line=dict(width=1,color='black')),
                hovertemplate=(
                    "<b>%{text}</b><br>"
                    "Year: %{x}<br>"
                    "Final Place: %{y}<br>"
                    "Poll: %{customdata[0]}<br>"
                    "Televote: %{customdata[1]}<br>"
                    "Jury Effect: %{customdata[2]}"
                ),
                text=seg_hover,
                customdata=seg_custom,
                name=country,
                opacity=abs(seg_opacity[0]) if len(seg_opacity) > 0 else 0.5
            ))
            segment_start = i  # start new segment

# Layout adjustments
fig.update_yaxes(autorange='reversed', title="Final Placement (Lower = Better)")
fig.update_xaxes(title="Year", dtick=1)
fig.update_traces(
    selected=dict(
        marker=dict(opacity=1),
        line=dict(width=3)
    ),
    unselected=dict(
        marker=dict(opacity=0.1),
        line=dict(color="rgba(150,150,150,0.1)")
    )
)
fig.update_layout(
    height=1080, width=1920,
    title="Eurovision Final Positions 2016–2023\n(Lines connect consecutive years only)",
    plot_bgcolor="#F5F5F2",
    paper_bgcolor="#F5F5F2",
    hovermode='closest',
    clickmode="event+select",
    dragmode=False
)

fig.show()

In [ ]:
# Precompute RGBA for all markers/lines
df_plot1["RGBA"] = [fade_to_bg(c, o) for c, o in zip(df_plot1["PointColor"], df_plot1["Opacity"])]

In [ ]:
app = Dash(__name__)

compute_opacity(df_plot1, k=0)

app.layout = html.Div([
    dcc.Store(id="selected-country", data=None),
    dcc.Graph(
        id="graph",
        figure=build_figure(),
        clear_on_unhover=True
    )
])

# Click callback
@app.callback(
    Output("selected-country", "data"),
    Input("graph", "clickData"),
    State("selected-country", "data")
)
def store_click(clickData, current_selected):
    if clickData is None:
        return current_selected
    clicked = clickData["points"][0]["hovertext"].split("<br>")[0]
    return None if current_selected == clicked else clicked

# -----------------------------
# Hover + click callback
# -----------------------------
@app.callback(
    Output("graph", "figure"),
    Input("graph", "hoverData"),
    Input("selected-country", "data")
)
def update_graph(hoverData, selected):
    hovered = None
    if hoverData:
        hovered = hoverData["points"][0]["hovertext"].split("<br>")[0]
    return build_figure(selected=selected, hovered=hovered)

In [ ]:

app.run(debug=True)

In [ ]:
fig = build_figure()

In [ ]:
fig.write_html("eurovision_jury_effect.html")

In [ ]:
len(df_plot[df_plot["Year"]=="2023F"])

In [ ]:
import plotly.graph_objects as go

fig = go.Figure()

# First, plot all lines as background (gray, low opacity)
for country in df_plot['Country'].unique():
    df_country = df_plot[df_plot['Country']==country].sort_values('Year')
    fig.add_trace(go.Scatter(
        x=df_country['Year'],
        y=df_country['Place'],
        mode='lines+markers',
        line=dict(color='lightgray', width=1),
        marker=dict(size=3, color='lightgray'),
        hoverinfo='skip',  # background lines don't show hover
        showlegend=False
    ))

# Then, plot foreground lines colored by JuryEffect with low opacity
for country in df_plot['Country'].unique():
    df_country = df_plot[df_plot['Country']==country].sort_values('Year')
    colors = [adjust_saturation(row['ColorNorm'], highlight=row['Highlight']) for idx,row in df_country.iterrows()]
    fig.add_trace(go.Scatter(
        x=df_country['Year'],
        y=df_country['Place'],
        mode='lines+markers',
        line=dict(color=colors[0], width=2),
        marker=dict(size=df_country['PointSize'], color=colors, line=dict(width=1, color='black')),
        hovertemplate=(
            "<b>%{text}</b><br>"
            "Year: %{x}<br>"
            "Final Place: %{y}<br>"
            "Poll: %{customdata[0]}<br>"
            "Televote: %{customdata[1]}<br>"
            "Jury Effect: %{customdata[2]}"
        ),
        text=[country]*len(df_country),
        customdata=df_country[['Poll_Rank','Place_Televote','JuryEffect']].values,
        name=country,
        opacity=0.7  # slightly transparent, will “pop” on hover
    ))

fig.update_yaxes(autorange='reversed', title="Final Placement (Lower = Better)")
fig.update_xaxes(title="Year", dtick=1)
fig.update_layout(
    height=720, width=1280,
    title="Eurovision Final Positions 2016–2023 (Hover Highlight Shows JuryEffect)",
    plot_bgcolor="#F5F5F2",
    paper_bgcolor="#F5F5F2",
    hovermode='closest'
)

fig.show()

In [ ]:
df = df_results_modified.copy()

In [ ]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

# Jury impact
df["jury_impact"] = df["Place_Televote"] - df["Place_Jury"]
df["abs_impact"] = df["jury_impact"].abs()

# Highlight threshold
THRESHOLD = 10
df["is_primary"] = df["abs_impact"] >= THRESHOLD

max_impact = df["abs_impact"].max()
df["norm_impact"] = df["jury_impact"] / max_impact

def interpolate_color(val):
    blue = np.array([33,113,181])
    bg = np.array([245,245,245])
    orange = np.array([217,95,2])

    if val > 0:
        return tuple((bg + val*(blue - bg)).astype(int))
    elif val < 0:
        return tuple((bg + abs(val)*(orange - bg)).astype(int))
    else:
        return tuple(bg.astype(int))

df["line_color"] = df["norm_impact"].apply(
    lambda x: f"rgb{interpolate_color(x)}"
)

# Fade non-primary toward neutral
df.loc[~df["is_primary"], "line_color"] = "rgb(220,220,220)"

def compute_width(norm_val):
    return abs(2 + norm_val * 6)   # base 2 → up to 8

years = sorted(df["Year"].unique())

fig = go.Figure()

x_vals = [0, 1, 2]
x_labels = ["Televote Rank", "Jury Rank", "Final Rank"]

from plotly.subplots import make_subplots
fig = make_subplots(
    rows=2,
    cols=4,
    subplot_titles=[str(y) for y in years[:8]],
    horizontal_spacing=0.05,
    vertical_spacing=0.12
)

x_vals = [0, 1, 2]

for i, year in enumerate(years[:8]):
    
    row = (i // 4) + 1
    col = (i % 4) + 1
    
    year_df = df[df["Year"] == year]
    
    # Draw non-highlighted first
    for _, r in year_df[~year_df["is_primary"]].iterrows():
        fig.add_trace(
            go.Scatter(
                x=x_vals,
                y=[r["Place_Televote"], r["Place_Jury"], r["Place"]],
                mode="lines",
                line=dict(
                    color="rgb(220,220,220)",
                    width=1.5
                ),
                showlegend=False
            ),
            row=row,
            col=col
        )
    
    # Highlighted entries
    for _, r in year_df[year_df["is_primary"]].iterrows():
        
        width = compute_width(r["norm_impact"])
        
        fig.add_trace(
            go.Scatter(
                x=x_vals,
                y=[r["Place_Televote"], r["Place_Jury"], r["Place"]],
                mode="lines",
                line=dict(
                    color=r["line_color"],
                    width=width
                ),
                showlegend=False
            ),
            row=row,
            col=col
        )
        
        # Add country name next to televote position
        fig.add_annotation(
            x=0,
            y=r["Place_Televote"],
            text=r["Country"],
            xanchor="right",
            showarrow=False,
            font=dict(size=9),
            row=row,
            col=col
        )


for r in range(1, 3):
    for c in range(1, 5):
        
        fig.update_xaxes(
            showline=False,
            showgrid=False,
            zeroline=False,
            tickmode="array",
            tickvals=[0,1,2],
            ticktext=["Televote","Jury","Final"],
            row=r,
            col=c
        )
        
        fig.update_yaxes(
            autorange="reversed",
            range=[26,1],
            showline=False,
            showgrid=True,
            gridcolor="rgba(0,0,0,0.05)",
            row=r,
            col=c
        )


fig.add_trace(go.Scatter(
    x=[None], y=[None],
    mode="lines",
    line=dict(color="rgb(33,113,181)", width=4),
    name="Jury Helped (Moved Up)"
))

fig.add_trace(go.Scatter(
    x=[None], y=[None],
    mode="lines",
    line=dict(color="rgb(217,95,2)", width=4),
    name="Jury Hurt (Moved Down)"
))

fig.add_trace(go.Scatter(
    x=[None], y=[None],
    mode="lines",
    line=dict(color="rgb(220,220,220)", width=2),
    name="Minimal Jury Impact"
))

fig.update_layout(
    height=1080,
    width=1920,
    template="simple_white",
    title={
        "text": "How Did the Jury Impact Public Favorites? (By Year)",
        "x": 0.5
    },
    legend=dict(
        orientation="h",
        y=-0.05,
        x=0.5,
        xanchor="center"
    )
)

In [ ]:
fig.write_image("eurovision_poll_effect.png", width=1920, height=1080, scale=2)

In [ ]:
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

# Assume df has columns: Country, Year, Poll_Rank, Place_Televote

# Fit global regression
z = np.polyfit(df["Poll_Rank"], df["Place_Televote"], 1)
p = np.poly1d(z)
df["predicted"] = p(df["Poll_Rank"])
df["residual"] = df["Place_Televote"] - df["predicted"]
df["abs_residual"] = df["residual"].abs()

# Threshold for outlier
THRESHOLD = 10
df["is_outlier"] = df["abs_residual"] >= THRESHOLD

# Colors per year
years = sorted(df["Year"].unique())
palette = px.colors.qualitative.Set2
year_colors = {year: palette[i % len(palette)] for i, year in enumerate(years)}

# Create figure
fig = go.Figure()

# Scatter points per year
for year in years:
    year_df = df[df["Year"] == year]
    
    # Normal points
    normal_df = year_df[~year_df["is_outlier"]]
    fig.add_trace(go.Scatter(
        x=normal_df["Poll_Rank"],
        y=normal_df["Place_Televote"],
        mode="markers",
        marker=dict(
            size=8,
            color=year_colors[year]
        ),
        name=str(year),
        showlegend=True
    ))
    
    # Outliers (same color, bigger marker, black edge)
    outlier_df = year_df[year_df["is_outlier"]]
    fig.add_trace(go.Scatter(
        x=outlier_df["Poll_Rank"],
        y=outlier_df["Place_Televote"],
        mode="markers+text",
        marker=dict(
            size=12,
            color=year_colors[year],   # keep year color
            line=dict(width=2, color="black")  # edge highlights outlier
        ),
        text=outlier_df["Country"],
        textposition="top center",
        name=str(year),  # same as year
        showlegend=False  # don't duplicate legend entries
    ))

# Regression line
x_range = np.linspace(df["Poll_Rank"].min(), df["Poll_Rank"].max(), 100)
fig.add_trace(go.Scatter(
    x=x_range,
    y=p(x_range),
    mode="lines",
    line=dict(color="black", width=3),
    name="Trend Line"
))

# Perfect consistency line
fig.add_trace(go.Scatter(
    x=[1, 26],
    y=[1, 26],
    mode="lines",
    line=dict(color="grey", dash="dash"),
    name="Perfect Poll = Televote"
))

# Statistics
corr = df["Poll_Rank"].corr(df["Place_Televote"])
r_squared = corr**2

# Layout
fig.update_layout(
    template="simple_white",
    height=1080,
    width=1920
    
)

fig.update_layout(
    title=dict(
        text="Poll vs Televote: Were Fans Consistent?<br>",
        x=0.5,
        font=dict(size=35)   # <-- change the title font size here
    )
)

fig.update_xaxes(
    title=dict(
        text="Pre-Contest Poll Rank",
        font=dict(size=24)  # <-- change x-axis title size
    ),
    tickfont=dict(size=14)   # <-- change x-axis tick numbers size
)

fig.update_yaxes(
    title=dict(
        text="Televote Rank",
        font=dict(size=24)  # <-- change y-axis title size
    ),
    tickfont=dict(size=14)   # <-- change y-axis tick numbers size
)

fig.update_layout(
    legend=dict(
        font=dict(size=24)   # <-- change legend text size
    )
)

In [ ]:
fig.write_image("eurovision_jury_effect.png", width=1920, height=1080, scale=2)